export const COLORS = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
};

export const Items = [
        {
            id:1,
            category: 'product',
            productName: 'Joyroom JR-H16 - Wireless Bluetooth',
            productPrice:2500,
            description: "Colorful gradient glow light for eye-catching!<br>Right Side support touch control. Fingerprint black technology, easier to use!<br>40mm high magnetic neodymium iron boron drive unit, new composite diaphragm, premium sound, super bass.<br>Premium US imported Chip, low power consumption, 300 hours of long battery life.",
            isOff:true,
            offPercentage:10,
            productImage:require('../dataBase/images/products/joy1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/products/joy1.png'),
                require('../dataBase/images/products/joy2.png'),
                require('../dataBase/images/products/joy3.png'),
            ],
        },
        {
            id:2,
            category: 'product',
            productName: 'Baseus D02 Pro - Bluetooth Headphone',
            productPrice:2800,
            description: "Every effort has been made to provide information on this site to be as accurate & updated as possible. However, Myshop is not responsible for any errors or omissions. All information on this site is provided on an “as is” basis, with no guarantees of completeness, accuracy, timeliness and without any warranties of any kind whatsoever, express or implied.",
            isOff:false,
            //offPercentage:10,
            productImage:require('../dataBase/images/products/base1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/products/base1.png'),
                require('../dataBase/images/products/base2.png'),
                
            ],
        },
        // {
        //     id:3,
        //     category: 'product',
        //     productName: 'Round Neck T.shirt Plain',
        //     productPrice:4000,
        //     description: "Incorporated in the year 2015, at New Delhi (Delhi, India), we “PNG Enterprises, are renowned organization affianced in Manufacturer and Trader premium quality range of Mens T Shirt, School Dress, Promotional T Shirt, Formal Shirt, Corporate Cap, Mens Sweatshirt, Promotional Cap, etc.",
        //     isOff:false,
        //     //offPercentage:10,
        //     productImage:require('../dataBase/images/products/black-tshirt.png'),
        //     isAvailable: false,
        //     productImageList:[
        //         require('../dataBase/images/products/black-tshirt.png'),
        //         require('../dataBase/images/products/orange-tshirt.png'),
        //         require('../dataBase/images/products/red-tshirt.png'),
        //         require('../dataBase/images/products/yellow-tshirt.png'),
        //     ],
        // },
        {
            id:4,
            category: 'accessories',
            productName: 'Baseus H13 - Aux 3.5mm Wired Earphone',
            productPrice:1650,
            description: "Use high-grade vocal shock-proof film and sound-emitting unit to reduce impedance and distortion, bring you a natural balanced sound, presenting clear mid-range, high-pitched and deep bass, with clear layers and retaining more musical details.",
            isOff:false,
            //offPercentage:10,
            productImage:require('../dataBase/images/accessories/Bas1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/accessories/Bas1.png'),
                require('../dataBase/images/accessories/bas2.png'),
                require('../dataBase/images/accessories/bas3.png'),
            ],
        },
        {
            id:5,
            category: 'accessories',
            productName: 'Baseus H19 - Wired Earphones',
            productPrice:1850,
            description: "Sensitive wire Control and Blind operation: Press a button to answer a call or play music via an integrated wire controller. Gently slide a button to choose the volume as you like by stepless adjustment.",
            isOff:false,
            //offPercentage:10,
            productImage:require('./images/accessories/Bh1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/accessories/Bh1.png'),
                require('../dataBase/images/accessories/bh2.png'),
               
            ],
        },
        {
            id:6,
            category: 'product',
            productName: 'Anker Soundcore - Life Q10 Wireless Bluetooth Headphones',
            productPrice:10500,
            description: "Hi-Res Certified Sound: The Hi-Res logo is a symbol of exceptional audio quality, awarded to audio devices capable of producing a highly accurate representation of what the artist intended to be heard. Unlike ordinary headphones, Life Q10 delivers sound up to 40 kHz for a richer listening experience.",
            isOff:false,
            //offPercentage:10,
            productImage:require('../dataBase/images/products/anker1.png'),
            isAvailable: false,
            productImageList:[
                require('../dataBase/images/products/anker1.png'),
                require('../dataBase/images/products/anker2.png'),
                require('../dataBase/images/products/anker3.png'),   
            ],
        },
        {
            id:7,
            category: 'product',
            productName: 'Skullcandy Cassette - Durable On-Ear Wireless Headphones',
            productPrice:10500,
            description: "Inspired by classic designs from the ‘80s and ‘90s, Cassette features style, comfort, durability, and sound quality far beyond its price. Stronger materials—including metal in the headband and high-quality ear cushions—ensure a long lifespan. A 1-year limited warranty picks up the slack.",
            isOff:false,
            //offPercentage:10,
            productImage:require('../dataBase/images/products/casse1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/products/casse1.png'),
                require('../dataBase/images/products/casse2.png'),
                require('../dataBase/images/products/casse3.png'),   
                require('../dataBase/images/products/casse4.png'),   
            ],
        },
        {
            id:8,
            category: 'accessories',
            productName: 'Asus Rog - Cetra II Core In Ear Gaming Earphone',
            productPrice:10500,
            description: "ROG Cetra II Core in-ear gaming headphones with liquid silicone rubber (LSR) drivers and a 3.5 mm connector compatible with PCs, laptops, mobile phones, ROG Phone 5, PlayStation 5, Xbox Series X/S and Nintendo Switch",
            isOff:true,
            offPercentage:10,
            productImage:require('../dataBase/images/accessories/rog1.png'),
            isAvailable: false,
            productImageList:[
                require('../dataBase/images/accessories/rog1.png'),
                require('../dataBase/images/accessories/rog2.png'),
                require('../dataBase/images/accessories/rog3.png'),      
            ],
        },
        // {
        //     id:9,
        //     category: 'accessories',
        //     productName: 'Skullcandy JIB S2DUYK-628 with Mic Earphones',
        //     productPrice:2200,
        //     description: "Every effort has been made to provide information on this site to be as accurate & updated as possible. However, Myshop is not responsible for any errors or omissions. All information on this site is provided on an “as is” basis, with no guarantees of completeness, accuracy, timeliness and without any warranties of any kind whatsoever, express or implied.",
        //     isOff:false,
        //     //offPercentage:10,
        //     productImage:require('../dataBase/images/accessories/sku1.png'),
        //     isAvailable: true,
        //     productImageList:[
        //         require('../dataBase/images/accessories/sku1.png'),
        //         require('../dataBase/images/accessories/sku2.png'),
        //         require('../dataBase/images/accessories/sku3.png'),      
        //     ],
        // },
        {
            id:10,
            category: 'product',
            productName: 'Skullcandy Riff - On-Ear Wired Headset',
            productPrice:6900,
            description: "Every effort has been made to provide information on this site to be as accurate & updated as possible. However, Myshop is not responsible for any errors or omissions. All information on this site is provided on an “as is” basis, with no guarantees of completeness, accuracy, timeliness and without any warranties of any kind whatsoever, express or implied.",
            isOff:true,
            offPercentage:10,
            productImage:require('../dataBase/images/products/riff1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/products/riff1.png'),
                require('../dataBase/images/products/riff2.png'),
                require('../dataBase/images/products/riff3.png'),      
            ],
        },
        {
            id:11,
            category: 'product',
            productName: 'SteelSeries Arctis 1 - Wired Headset',
            productPrice:11000,
            description: "The Arctis 1 is a multi-platform gaming headset that can also be used as headphones on the go. Enjoy Arctis' award-winning success wherever you are with its detachable microphone and sleek low-profile style.",
            isOff:false,
            //offPercentage:10,
            productImage:require('../dataBase/images/products/steel1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/products/steel1.png'),
                require('../dataBase/images/products/steel2.png'),
                require('../dataBase/images/products/steel3.png'),      
            ],
        },
        {
            id:12,
            category: 'accessories',
            productName: 'Sony Wireless Noise Cancelling Headphones',
            productPrice:34500,
            description: "Dual microphones - one feed-forward and one feed-back - on the surface of the headphones catch more of the ambient sounds of your surroundings, whether it's in-flight noise, city traffic or office chatter.",
            isOff:true,
            offPercentage:10,
            productImage:require('../dataBase/images/accessories/sony1.png'),
            isAvailable: true,
            productImageList:[
                require('../dataBase/images/accessories/sony1.png'),
                require('../dataBase/images/accessories/sony2.png'),
                require('../dataBase/images/accessories/sony3.png'),      
            ],
        },
];